application_port: 8000

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "bitcoin_dashboard"
  
bitcoin:
  rpc_url: "http://localhost:18443"
  rpc_user: "alice"
  rpc_password: "password",