services:
  bitcoind:
    image: lncm/bitcoind:v25.0
    container_name: bitcoind
    user: "0:0"
    command:
      - -regtest=1
      - -server=1
      - -txindex=1
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=alice
      - -rpcpassword=password
      - -fallbackfee=0.0001
      - -datadir=/home/bitcoin/.bitcoin
    ports:
      - "18443:18443" # RPC
      - "18444:18444" # P2P
    volumes:
      - ./datadir/node0:/home/bitcoin/.bitcoin
    networks:
      - bpd-network

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-bitcoin_dashboard}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    command: postgres -N 1000
    networks:
      - bpd-network

networks:
  bpd-network:
    driver: bridge
